branch-defaults:
  master:
    environment: tempmed3Dmod-dev
global:
  application_name: tempmed3Dmod
  default_ec2_keyname: NewRuben
  default_platform: Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: git
